### ISSUE TITLE
[Research] Making SIGNER_LIMIT Dynamic 

### ISSUE THREAD

**Issue by ChainSafeSystems** [goerli/eips-poa#10]
- [ ]  removing the need for the SIGNER_LIMIT to be static 
- [ ] ...edit and add more...

**Comment by soc1c** [comment]
a5941f6faea2abdd7322a88ba1feecce4df77e97 proposes

* **`SIGNER_LIMIT`**: Number of consecutive blocks out of which a signer may only sign one. It must be `floor(SIGNER_COUNT / 3) + 1` to enforce at least `> 33%` consensus on a proof-of-authority chain.
