### ISSUE TITLE
Significantly increase MIN_WAIT

### ISSUE THREAD

**Issue by soc1c** [goerli/eips-poa#6]
> Observations on Görli show that we have way too many reorganizations due to the out-of-turn delay often being lower than the network latency. I would strongly encourage to introduce something like a **`MIN_WAIT`** of `5000ms`, so that the out-of-turn delay is something around `MIN_WAIT + rand(SIGNER_COUNT * 500ms)`.

> Agreed, with just the random delay out of turn blocks may be published at essentially the same time as the in-turn block. I'd highly recommend the minimum wait time and the 500ms multiplier should both be configurable like block period tends to be. The best values for them are highly affected by network latency and the chosen block period.

ref https://github.com/ethereum/EIPs/pull/1570#discussion_r238999003

**Comment by soc1c** [comment]
also

> Proposal: Add two configurable options for the Clique algorithm:
>   - OUT_OF_TURN_DELAY_MULTIPLIER
> 	  - Currently explicitly 500ms in the spec
>   - MIN_OUT_OF_TURN_DELAY
> 	  - New concept so Rinkeby and Görli are effectively using 0ms
> 	  - Absolute minimum amount of time to wait before publishing an out of turn block
> Delay calculation is then: 
> MIN_OUT_OF_TURN_DELAY + rand(SIGNER_COUNT * OUT_OF_TURN_DELAY_MULTIPLER)
> 
> On low latency networks the current settings may be enough but a geographically dispersed network like Görli may increase both options to ensure the out of turn delay exceeds the network latency and out of turn blocks aren’t created unnecessarily.

ref https://docs.google.com/document/d/1tmsr66sAPJmIZfSy5zck1uxnLzaXYxvzTNL5CF1pJQ0/edit#

**Comment by soc1c** [comment]
1193d3d44d76bbb2124adbcccce7a322a355687d proposes

* **`MIN_WAIT`**: The minimum time to wait for an out-of-turn block to be published. It is suggested to set it to `BLOCK_PERIOD / 2`.

with 

* If the signer is out-of-turn, delay signing by `MIN_WAIT + rand(SIGNER_COUNT * 500ms)`.

**Comment by gusan-one** [comment]
Im facing this issues using 4 signers poa network. Network splits in two. 2 signers have 3 last blocks that differ from 3 last blocks of other 2 signers. Network just locks. Is there a solution for that issue?
