### ISSUE TITLE
In-turn signers should override out-of-turn blocks

### ISSUE THREAD

**Issue by soc1c** [goerli/eips-poa#8]
> We should add that in-turn signers should continue to produce their block even if they receive an out-of-turn block for that height before they publish their in-turn one. Otherwise clock drift and the lack of a minimum delay for out of turn blocks can cause an online in-turn validator from publishing their block and cause problems for the network. There's a more detailed explanation of how this happens at https://docs.google.com/document/d/1tmsr66sAPJmIZfSy5zck1uxnLzaXYxvzTNL5CF1pJQ0/edit#heading=h.ic4qz2ybx51

ref https://github.com/ethereum/EIPs/pull/1570#discussion_r239238624

**Comment by ChainSafeSystems** [comment]
**Proposal:** Add two configurable options for the Clique algorithm:

`OUT_OF_TURN_DELAY_MULTIPLIER`
Currently explicitly 500ms in the spec

`MIN_OUT_OF_TURN_DELAY`
New concept so Rinkeby and Görli are effectively using 0ms.
Absolute minimum amount of time to wait before publishing an out of turn block

Delay calculation is then: 
`MIN_OUT_OF_TURN_DELAY + 
rand(SIGNER_COUNT * OUT_OF_TURN_DELAY_MULTIPLER)`

**Comment by soc1c** [comment]
9f5cfc8762e032ac2d3605679751ff8dec06743c proposes

 * Each singer is allowed to sign maximum one out of **`SIGNER_LIMIT`** consecutive blocks. The order is not fixed, but in-turn signing weighs more (**`DIFF_INTURN`**) than out of turn one (**`DIFF_NOTURN`**). In case an out-of-turn block is received, an **in-turn signer should continue to publish their block** to ensure the chain always prefers in-turn blocks in any case. This prevents in-turn validators to be prevented from publishing their block and potential network problems.
